export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const GETSERVICECENTER_SUCCESS = 'GETSERVICECENTER_SUCCESS'
export const GETSERVICECENTER_FAIL = 'GETSERVICECENTER_FAIL'

export const SERVICECENTER_ADD_SUCCESS = 'SERVICECENTER_ADD_SUCCESS'
export const SERVICECENTER_ADD_FAIL = 'SERVICECENTER_ADD_FAIL'

export const GETVACANTADMIN_SUCCESS = 'GETVACANTADMIN_SUCCESS'
export const GETVACANTADMIN_FAIL = 'GETVACANTADMIN_FAIL'

export const SERVICECENTER_DELETE_FAIL = 'SERVICECENTER_DELETE_FAIL'
export const SERVICECENTER_DELETE_SUCCESS = 'SERVICECENTER_DELETE_SUCCESS'

export const UPDATEVACANTADMIN_SUCCESS = 'UPDATEVACANTADMIN_SUCCESS'
export const UPDATE_ASSIGNED_ADMIN_SUCCESS = 'UPDATE_ASSIGNED_ADMIN_SUCCESS'

export const ASSIGNSERVICECENTER_SUCCESS = 'ASSIGNSERVICECENTER_SUCCESS'
export const ASSIGNSERVICECENTER_FAIL = 'ASSIGNSERVICECENTER_FAIL'

export const SERVICECENTER_UPDATE_SUCCESS = 'SERVICECENTER_UPDATE_SUCCESS'
export const SERVICECENTER_UPDATE_FAIL = 'SERVICECENTER_UPDATE_FAIL'

export const GETSUPERADMIN_SUCCESS = 'GETSUPERADMIN_SUCCESS'
export const GETSUPERADMIN_FAIL = 'GETSUPERADMIN_FAIL'

export const SUPERADMIN_ADD_SUCCESS = 'SUPERADMIN_ADD_SUCCESS'
export const SUPERADMIN_ADD_FAIL = 'SUPERADMIN_ADD_FAIL'

export const UPDATESUPERADMIN_SUCCESS = 'UPDATESUPERADMIN_SUCCESS'
export const UPDATESUPERADMIN_FAIL = 'UPDATESUPERADMIN_FAIL'

export const SUPERADMIN_DELETE_SUCCESS = 'SUPERADMIN_DELETE_SUCCESS'
export const SUPERADMIN_DELETE_FAIL = 'SUPERADMIN_DELETE_FAIL'

export const GETADMIN_SUCCESS = 'GETADMIN_SUCCESS'
export const GETADMIN_FAIL = 'GETADMIN_FAIL'

export const ADMIN_ADD_SUCCESS = 'ADMIN_ADD_SUCCESS'
export const ADMIN_ADD_FAIL = 'ADMIN_ADD_FAIL'

export const ADMIN_DELETE_SUCCESS = 'ADMIN_DELETE_SUCCESS'
export const ADMIN_DELETE_FAIL = 'ADMIN_DELETE_FAIL'

export const UPDATEADMIN_SUCCESS = 'UPDATEADMIN_SUCCESS'
export const UPDATEADMIN_FAIL = 'UPDATEADMIN_FAIL'

export const GETPROFILE_SUCCESS = 'GETPROFILE_SUCCESS'
export const GETPROFILE_FAIL = 'GETPROFILE_FAIL'

export const UPDATEPROFILE_SUCCESS = 'UPDATEPROFILE_SUCCESS'
export const UPDATEPROFILE_FAIL = 'UPDATEPROFILE_FAIL'

export const GETBIKEMODEL_SUCCESS = 'GETBIKEMODEL_SUCCESS'
export const GETBIKEMODEL_FAIL = 'GETBIKEMODEL_FAIL'

export const BIKEMODEL_ADD_SUCCESS = 'BIKEMODEL_ADD_SUCCESS'
export const BIKEMODEL_ADD_FAIL = 'BIKEMODEL_ADD_FAIL'

export const BIKEMODEL_DELETE_SUCCESS = 'BIKEMODEL_DELETE_SUCCESS'
export const BIKEMODEL_DELETE_FAIL = 'BIKEMODEL_DELETE_FAIL'

export const UPDATEBIKEMODEL_SUCCESS = 'UPDATEBIKEMODEL_SUCCESS'
export const UPDATEBIKEMODEL_FAIL = 'UPDATEBIKEMODEL_FAIL'

export const GETBIKE_SUCCESS = 'GETBIKE_SUCCESS'
export const GETBIKE_FAIL = 'GETBIKE_FAIL'

export const BIKE_ADDORUPDATE_SUCCESS = 'BIKE_ADDORUPDATE_SUCCESS'
export const BIKE_ADDORUPDATE_FAIL = 'BIKE_ADDORUPDATE_FAIL'

export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_FAIL = 'BOOKING_FAIL'

export const GETSERVICECENTERBYID_SUCCESS = 'GETSERVICECENTERBYID_SUCCESS'
export const GETSERVICECENTERBYID_FAIL = 'GETSERVICECENTERBYID_FAIL'