export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const GETSERVICECENTER_SUCCESS = 'GETSERVICECENTER_SUCCESS'
export const GETSERVICECENTER_FAIL = 'GETSERVICECENTER_FAIL'

export const SERVICECENTER_ADD_SUCCESS = 'SERVICECENTER_ADD_SUCCESS'
export const SERVICECENTER_ADD_FAIL = 'SERVICECENTER_ADD_FAIL'

export const GETVACANTADMIN_SUCCESS = 'GETVACANTADMIN_SUCCESS'
export const GETVACANTADMIN_FAIL = 'GETVACANTADMIN_FAIL'

export const SERVICECENTER_DELETE_FAIL = 'SERVICECENTER_DELETE_FAIL'
export const SERVICECENTER_DELETE_SUCCESS = 'SERVICECENTER_DELETE_SUCCESS'

export const UPDATEVACANTADMIN_SUCCESS = 'UPDATEVACANTADMIN_SUCCESS'



